### ISSUE TITLE
Could we block ads? Should we block ads?

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#4]

**Comment by simonw** [comment]
My initial hunch was no because they're part of the site design, but they are REALLY big.

![image](https://user-images.githubusercontent.com/9599/158028536-e2d5752f-ccb3-45b9-a97e-902ffee33eda.png)

This JavaScript hides them all for the LA Times:
```javascript
document.querySelectorAll('[data-ad-rendered]').forEach(el => el.style.display = 'none')
```

**Comment by simonw** [comment]
Here's what this does:
```
shot-scraper https://www.latimes.com/ \
  --quality 80 \
  --width 1600 \
  --height 1600 \
  --wait 2000 \
  --javascript "document.querySelectorAll('[data-ad-rendered]').forEach(el => el.style.display = 'none')" \
  -o latimes.jpg
```
![latimes](https://user-images.githubusercontent.com/9599/158028630-459d90de-27aa-4f42-9924-dbc1810e2630.jpg)

**Comment by simonw** [comment]
Using this selector instead also gets rid of that Terms of Service / Privacy policy block:

    document.querySelectorAll('[data-ad-rendered],#ensNotifyBanner').forEach(el => el.style.display = 'none')

![latimes](https://user-images.githubusercontent.com/9599/158028734-b3c43920-976c-4652-9ebc-18b4e14ec967.jpg)

**Comment by simonw** [comment]
If you're going to start doing this I suggest switching to the YAML configuration format, since that makes it easier to embed custom JavaScript. You could have two files like this:

`latimes.yml`
```yaml
- url: https://www.latimes.com/
  output: latimes.jpg
  width: 1600
  height: 1600
  quality: 80
  wait: 2000
  javascript: |
    document.querySelectorAll(
      '[data-ad-rendered],#ensNotifyBanner'
    ).forEach(el => el.style.display = 'none')
```

`nytimes.yml`
```yaml
- url: https://www.nytimes.com/
  output: nytimes.jpg
  width: 1600
  height: 1600
  quality: 80
  wait: 2000
```

Then the script could run one of these two commands depending on the matrix setting:

    shot-scraper multi latimes.yml
    # or
    shot-scraper multi nytimes.yml

The YAML approach makes it easier to have custom JavaScript depending on the site.
